# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: #l'entité a utiliser pour la connexion
            algorithm: bcrypt #methode de cryptage du mdp
            cost: 12 #le nombre de fois ou le mdp est crypté

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: /admin, roles: ROLE_ADMIN } #l'utilisateur qui a le role ROLE_ADMIN peut se connecter a /admin
        #- { path: /profile, roles: ROLE_ADMIN } #l'utilisateur qui a le role ROLE_ADMIN peut se connecter a /profile
        - { path: /profile, roles: ROLE_USER} #l'utilisateur qui a le role ROLE_USER peut se connecter a /profile

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER # le ROLE_ADMIN et supperieur a ROLE_USER car ROLE_ADMIN est la clé et ROLE_USER est la valeur
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User  #l'entité utiliser pour la connexion
                property: username     #la propriétè qui sert de pseudo

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: our_db_provider
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                login_path: security.login
                check_path: security.login
                default_target_path: security.redirect.login #la route ou on veut redireger l'user apres sa connexion
                csrf_token_generator: security.csrf.token_manager

            logout:
                path:   security.logout
                target: app.index
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
