# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    admin.service.utiles.string:
        class: adminBundle\Service\Utiles\StringService

    admin.service.utiles.unlik:
        class: adminBundle\Service\Utiles\UnlikService
        arguments: ['%upload_dir%']

    admin.service.upload.upload:
        class: adminBundle\Service\Upload\UploadService
        arguments: ['@admin.service.utiles.string','%upload_dir%']

    admin.listener.produitlistener:
        class: adminBundle\Listener\ProduitListener
        arguments: ["@admin.service.upload.upload",'@admin.service.utiles.unlik']
        tags:
            - { name: doctrine.orm.entity_listener }

    admin.twig.extention:
        class: adminBundle\Twig\AppExtension
        arguments: [ '@doctrine','@twig']
        tags:
            - { name: twig.extension}


