<?php
/**
 * Created by PhpStorm.
 * User: wamobi9
 * Date: 26/01/17
 * Time: 12:08
 */

namespace AppBundle\Command;


use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class CustomCommand extends ContainerAwareCommand
{
    protected function configure()
    {
        $this->setName('app2');
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }


}