<?php
/**
 * Created by PhpStorm.
 * User: wamobi9
 * Date: 26/01/17
 * Time: 11:54
 */

namespace AppBundle\Command;


use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;



class UserAddRoleCommand extends ContainerAwareCommand
{
    protected function configure()
    {
        $this->setName('app:user:role:add')// le nom de la commande
        ->setDescription('Add role to an user')// description de la commande
        ->addArgument('username', InputArgument::REQUIRED, 'donner un nom')// ici il faut entrer un nom  et 'donner un nom' sera afficher comme message avec  app:user:role:add --h
        ->addArgument('role', InputArgument::REQUIRED, 'Entrer le role');


        //parent::configure(); /// TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $username = $input->getArgument('username'); // on recupere le nom de l'argument definit plus haut
        $role = $input->getArgument('role');


        $output->writeln("$username // $role");// affiche le retour sur la console pour  voir ce que on a ecrit

        $container= $this->getContainer();// on recupere  le container des service de symfony
        $doctine= $container->get('doctrine'); // service doctine
        $em=$doctine->getManager();// service manager

        $rcUser=$doctine->getRepository('AppBundle:User')->findOneBy(['username'=>$username]);// on recuprer user dans la table user selon son username
        $rcrole= $doctine->getRepository('AppBundle:Role')->findOneBy(['name'=>'ROLE_'. strtoupper($role)]);// on concatine ROLE_ avec ce que on va saisir dans la console
        $rcUser->addRole($rcrole);// ajoute le role pour le username ici c'est addRole car c'est une relation ManyToMany

        $em->persist($rcUser);//
        $em->flush();



        //parent::execute($input, $output); // TODO: Change the autogenerated stub
    }


}